##   Escuela Politécnica Nacional   
## Ingeniería de Ciencias de la Computación   
##  Métodos Numéricos   
### Descomposición LU
### Aubertin Ochoa          
### 05/02/2025

[Link GITHUB](https://github.com/auber-8a/Metodos_Numericos/blob/1c0274c81ae5774c9a3ef093cda28a52459d4894/Descomposicion_LU.ipynb) 

# <span style="color:orange"> *Ejercicios Propuestos* </span>
## <span style="color:orange"> *1. Realice las siguientes multiplicaciones matriz-matriz:* </span>


### a.
$$
\begin{bmatrix} 
2 & -3 \\ 
3 & -1 
\end{bmatrix}   
     
\begin{bmatrix} 
1 & 5 \\ 
2 & 0 
\end{bmatrix}
$$

In [1]:
import numpy as np

def multiplicacion(a, b):
    return np.dot(a, b)

In [2]:
A1 = np.array([[2, -3], [3, -1]])
A2 = np.array([[1, 5], [2, 0]])

multiplicacion(A1, A2)

array([[-4, 10],
       [ 1, 15]])

### b.
$$
\begin{bmatrix} 
2 & -3 \\ 
3 & -1 
\end{bmatrix}
\begin{bmatrix} 
1 & 5 & -4 \\ 
-3 & 2 & 0 
\end{bmatrix}
$$

In [4]:
B1 = np.array([[2, -3], [3,-1]])
B2 = np.array([[1, 5, -4], [-3, 2, 0]])

multiplicacion(B1, B2)

array([[ 11,   4,  -8],
       [  6,  13, -12]])

### c.
$$
\begin{bmatrix} 
2 & -3 & 1 \\ 
4 & 3 & 0 \\ 
5 & 2 & -4 
\end{bmatrix}
\begin{bmatrix} 
0 & 1 & -2 \\ 
1 & 0 & -1 \\ 
2 & 3 & -2 
\end{bmatrix}
$$

In [5]:
C1 = np.array([[2, -3, 1], [4, 3, 0], [5, 2, -4]])
C2 = np.array([[0, 1, -2], [1, 0, -1], [2, 3, -2]])

multiplicacion(C1, C2)

array([[ -1,   5,  -3],
       [  3,   4, -11],
       [ -6,  -7,  -4]])

### d.
$$
\begin{bmatrix} 
2 & 1 & 2 \\ 
-2 & 3 & 0 \\ 
2 & -1 & 3 
\end{bmatrix}
\begin{bmatrix} 
1 & -2 \\ 
-4 & 1 \\ 
0 & 2 
\end{bmatrix}
$$

In [6]:
D1 = np.array([[2, 1, 2], [-2, 3, 0], [2, -1, 3]])
D2 = np.array([[1, -2], [-4, 1], [0, 2]])

multiplicacion(D1, D2)

array([[ -2,   1],
       [-14,   7],
       [  6,   1]])

# <span style="color:orange"> *2. Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:* </span>

### a.
$$
\begin{bmatrix} 
4 & 2 & 6 \\ 
3 & 0 & 7 \\ 
-2 & -1 & -3 
\end{bmatrix}
$$

In [16]:
import numpy as np

def inversa_de_lista(matrices):
    inversas = []
    for i, M in enumerate(matrices):
        det = np.linalg.det(M)
        if det != 0:
            inv = np.linalg.inv(M)
            inversas.append(inv)
            print(f"Matriz es no singular y su inversa es:\n{inv}\n")
        else:
            inversas.append(None)
            print(f"Matriz es singular y no tiene inversa.\n")
    return inversas

def inversa(A):
    det = np.linalg.det(A)
    if det != 0:
        inv = np.linalg.inv(A)
        return inv
    else:
        print("La matriz proporcionada es singular y no tiene inversa.")
        return None

In [23]:
matrices = [
    np.array([[4, 2, 6], [3, 0, 7], [-2, -1, -3]]),
   
]

x = inversa_de_lista(matrices)

Matriz es singular y no tiene inversa.



### b.
$$
\begin{bmatrix} 
1 & 2 & 0 \\ 
2 & 1 & -1 \\ 
3 & 1 & 1 
\end{bmatrix}
$$

In [24]:
matrices = [
    np.array([[1, 2, 0], [2, 1, -1], [3, 1, 1]])
   
]

x = inversa_de_lista(matrices)

Matriz es no singular y su inversa es:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]



### c.
$$
\begin{bmatrix} 
1 & 1 & -1 & 1 \\ 
1 & 2 & -4 & -2 \\ 
2 & 1 & 1 & 5 \\ 
-1 & 0 & -2 & -4 
\end{bmatrix}
$$

In [25]:
matrices = [
    np.array([[1, 1, -1, 1], [1, 2, -4, -2], [2, 1, 1, 5], [-1, 0, -2, -4]])
   
]

x = inversa_de_lista(matrices)

Matriz es singular y no tiene inversa.



### d.
$$
\begin{bmatrix} 
4 & 0 & 0 & 0 \\ 
6 & 7 & 0 & 9 \\ 
9 & 11 & 1 & 0 \\ 
5 & 4 & 1 & 3 
\end{bmatrix}
$$

In [26]:
matrices = [
    np.array([[4, 0, 0, 0], [6, 7, 0, 0], [9, 11, 1, 0], [5, 4, 1, 1]])
   
]

x = inversa_de_lista(matrices)

Matriz es no singular y su inversa es:
[[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]



# <span style="color:orange"> *3. Resuelva los sistemas lineales $ 4 \times 4 $ que tienen la misma matriz de coeficientes:* </span>

### Primer sistema:
$$
\begin{aligned}
    x_1 - x_2 + 2x_3 - x_4 &= 6, \\
    x_1 - x_3 + x_4 &= 4, \\
    2x_1 + x_2 + 3x_3 - 4x_4 &= -2, \\
    -x_2 + x_3 - x_4 &= 5.
\end{aligned}
$$


### Segundo sistema:
$$
\begin{aligned}
    x_1 - x_2 + 2x_3 - x_4 &= 1, \\
    x_1 - x_3 + x_4 &= 1, \\
    2x_1 + x_2 + 3x_3 - 4x_4 &= 2, \\
    -x_2 + x_3 - x_4 &= -1.
\end{aligned}
$$

In [3]:
import numpy as np

A = np.array([[1, -2, 2, -1], [1, 0, -1, 1], [2, 1, 3, -4], [0, -1, 1, -1]])
b1 = np.array([6, 4, -2, 5])
b2 = np.array([1, 1, 2, -1])

x1 = np.linalg.solve(A, b1)
x2 = np.linalg.solve(A, b2)

print("Solución del primer sistema:\n", x1)
print("\nSolución del segundo sistema:\n", x2)

Solución del primer sistema:
 [ 2.14285714 -6.85714286 -8.         -6.14285714]

Solución del segundo sistema:
 [1.14285714 1.14285714 2.         1.85714286]


# <span style="color:orange"> *4. Encuentre los valores de $ A $ que hacen que la siguiente matriz sea singular.* </span>
 
$$
A =
\begin{bmatrix} 
1 & -1 & \alpha \\ 
2 & 2 & 1 \\ 
0 & \alpha & -\frac{3}{2} 
\end{bmatrix}
$$

In [9]:
import sympy as sp

alpha = sp.symbols('alpha')

A = sp.Matrix([
    [1, -1, alpha],
    [2, 2, 1],
    [0, alpha, -3/2]
])

det_A = A.det()

singular_values = sp.solve(det_A, alpha)

print("Valores de α que hacen la matriz singular:", singular_values)

Valores de α que hacen la matriz singular: [-1.50000000000000, 2.00000000000000]


# <span style="color:orange"> *5. Resuelva los siguientes sistemas lineales:* </span>

### a.
$$
\begin{bmatrix} 
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
-1 & 0 & 1 
\end{bmatrix}
\begin{bmatrix} 
2 & 3 & -1 \\ 
0 & -2 & 1 \\ 
0 & 0 & 3 
\end{bmatrix}
\begin{bmatrix} 
x_1 \\ 
x_2 \\ 
x_3 
\end{bmatrix}
=
\begin{bmatrix} 
2 \\ 
-1 \\ 
1 
\end{bmatrix}
$$

### b.
$$
\begin{bmatrix} 
2 & 0 & 0 \\ 
-1 & 1 & 0 \\ 
3 & 2 & -1 
\end{bmatrix}
\begin{bmatrix} 
1 & 1 & 1 \\ 
0 & 1 & 2 \\ 
0 & 0 & 1 
\end{bmatrix}
\begin{bmatrix} 
x_1 \\ 
x_2 \\ 
x_3 
\end{bmatrix}
=
\begin{bmatrix} 
-1 \\ 
3 \\ 
0 
\end{bmatrix}
$$

In [4]:
def resolver_LU(L: np.ndarray, U: np.ndarray, b: np.ndarray) -> np.ndarray:

    n = L.shape[0]

    # Sustitución hacia adelante (Ly = b)
    y = np.zeros((n, 1), dtype=float)
    for i in range(n):
        y[i] = (b[i] - np.sum(L[i, :i] * y[:i])) / L[i, i]

    # Sustitución hacia atrás (Ux = y)
    x = np.zeros((n, 1), dtype=float)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.sum(U[i, i + 1:] * x[i + 1:])) / U[i, i]

    return x

In [5]:
import numpy as np

# Sistema a
L_a = np.array([[1, 0, 0],
                [2, 1, 0],
                [-1, 0, 1]], dtype=float)

U_a = np.array([[2, 3, -1],
                [0, -2, 1],
                [0, 0, 3]], dtype=float)

b_a = np.array([[2], [-1], [1]], dtype=float)

# Sistema b
L_b = np.array([[2, 0, 0],
                [-1, 1, 0],
                [3, 2, -1]], dtype=float)

U_b = np.array([[1, 1, 1],
                [0, 1, 2],
                [0, 0, 1]], dtype=float)

b_b = np.array([[-1], [3], [0]], dtype=float)


# Resolver los sistemas
sol_a = resolver_LU(L_a, U_a, b_a)
sol_b = resolver_LU(L_b, U_b, b_b)

sol_a, sol_b


(array([[-0.5       ],
        [ 2.16666667],
        [-0.66666667]]),
 array([[ 14.5],
        [-17.5],
        [ 10. ]]))

# <span style="color:orange"> *6. Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU con $ l_{ii} = 1 $ para todas las $ i $.* </span>

### **a.**
$$
\begin{bmatrix}
2 & -1 & 1 \\
3 & 3 & 9 \\
3 & 3 & 5
\end{bmatrix}
$$

### **b.**
$$
\begin{bmatrix}
1.012 & -2.132 & 3.104 \\
-2.132 & 4.096 & -7.013 \\
3.104 & -7.013 & 0.014
\end{bmatrix}
$$

### **c.**
$$
\begin{bmatrix}
2 & 0 & 0 & 0 \\
1 & 1.5 & 0 & 0 \\
0 & -3 & 0.5 & 0 \\
2 & -2 & 1 & 1
\end{bmatrix}
$$

### **d.**
$$
\begin{bmatrix}
2.1756 & 4.0231 & -2.1732 & 5.1967 \\
-4.0231 & 6.0000 & 0 & 1.1973 \\
-1.0000 & -5.2107 & 1.1111 & 0 \\
6.0235 & 7.0000 & 0 & -4.1561
\end{bmatrix}
$$

In [36]:
from scipy.linalg import lu

# Definir matrices
matrices = [
    np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]]),
    np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]),
    np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]]),
    np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]])
]

# Factorización LU
for i, M in enumerate(matrices):
    P, L, U = lu(M)
    print(f"\nMatriz {i+1}:")
    print("\nL:\n", L)
    print("\nU:\n", U)


Matriz 1:

L:
 [[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]

U:
 [[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

Matriz 2:

L:
 [[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]

U:
 [[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]

Matriz 3:

L:
 [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]]

U:
 [[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]

Matriz 4:

L:
 [[ 1.          0.          0.          0.        ]
 [-0.66790072  1.          0.          0.        ]
 [ 0.3611

# <span style="color:orange"> *7. Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.* </span>



### **a.**
$$
\begin{aligned}
2x_1 - x_2 + x_3 &= -1, \\
3x_1 + 3x_2 + 9x_3 &= 0, \\
3x_1 + 3x_2 + 5x_3 &= 4.
\end{aligned}
$$

### **b.**
$$
\begin{aligned}
1.012x_1 - 2.132x_2 + 3.104x_3 &= 1.984, \\
-2.132x_1 + 4.096x_2 - 7.013x_3 &= -5.049, \\
3.104x_1 - 7.013x_2 + 0.014x_3 &= -3.895.
\end{aligned}
$$

### **c.**
$$
\begin{aligned}
2x_1 &= 3, \\
x_1 + 1.5x_2 &= 4.5, \\
-3x_2 + 0.5x_3 &= -6.6, \\
2x_1 - 2x_2 + x_3 + x_4 &= 0.8.
\end{aligned}
$$

### **d.**
$$
\begin{aligned}
2.1756x_1 + 4.0231x_2 - 2.1732x_3 + 5.1967x_4 &= 17.102, \\
-4.0231x_1 + 6.0000x_2 + 1.1973x_4 &= -6.1593, \\
-1.0000x_1 - 5.2107x_2 + 1.1111x_3 &= 3.0004, \\
6.0235x_1 + 7.0000x_2 - 4.1561x_4 &= 0.0000.
\end{aligned}
$$

In [38]:
import numpy as np

def lu_decomposition(A):
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()

    for i in range(n):
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j] = U[j] - L[j, i] * U[i]

    return L, U

def SustitucionAdelante(L, b):
    n = L.shape[0]
    y = np.zeros(n)

    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])

    return y

def SustitucionAtras(U, y):
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x

def solve_lu(A, b):
    L, U = lu_decomposition(A)
    y = SustitucionAdelante(L, b)
    x = SustitucionAtras(U, y)
    return x

A_list = [
    np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]], dtype=float),
    np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]], dtype=float),
    np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]], dtype=float),
    np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]], dtype=float)
]

b_list = [
    np.array([-1, 0, 4], dtype=float),
    np.array([1.984, -5.049, -3.895], dtype=float),
    np.array([3, 4.5, -6.6, 0.8], dtype=float),
    np.array([17.102, -6.1593, 3.0004, 0], dtype=float)
]

solutions = [solve_lu(A, b) for A, b in zip(A_list, b_list)]

for i, solution in enumerate(solutions):
    print(f"Solución del sistema {chr(97+i)}: {solution}")

Solución del sistema a: [ 1.  2. -1.]
Solución del sistema b: [1. 1. 1.]
Solución del sistema c: [ 1.5  2.  -1.2  3. ]
Solución del sistema d: [2.9398512  0.0706777  5.67773512 4.37981223]
